wandb_version: 1

learning_rate:
  desc: null
  value: 0.0005
batch_size:
  desc: null
  value: 128
clip:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717316448.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.8
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
