
file_name: 'indices'

receptive_field_size : 127
z_dim : 5
seq_len : 127
clip : 0.01
loss_func: 'WGAN' # "WGAN", "WGAN-GP", "VANILLA"

num_epochs : 400
batch_size : 128
lr : 0.0005
device : "cuda:0"
n_critic: 5
num_G: 5